"""
Auto-generated Flask backend for project: ToonHub
Generated by Backend Agent. Serves the frontend at clean numeric/root URLs
(no .html in any URL) and exposes JSON APIs the frontend calls via fetch().
"""
import os
import datetime
from flask import Flask, send_from_directory, jsonify, request
from flask_cors import CORS
from pymongo import MongoClient
from dotenv import load_dotenv

load_dotenv()

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
FRONTEND_DIR = os.path.join(BASE_DIR, "frontend")

app = Flask(__name__, static_folder=FRONTEND_DIR, static_url_path="")
CORS(app)

mongo_client = MongoClient(os.environ.get("MONGO_URI", "mongodb://localhost:27017"))
db = mongo_client[os.environ.get("MONGO_DB_NAME", "generated_website_db")]

PROJECT_SLUG = "toonhub"
db_collections = {
    "contact_messages": db["project_toonhub_contact_messages"],
    "testimonials": db["project_toonhub_testimonials"],
}


@app.route("/")
def home():
    # Serves index.html with a clean root URL — never /index.html
    return send_from_directory(FRONTEND_DIR, "index.html")


@app.route("/style.css")
def style():
    return send_from_directory(FRONTEND_DIR, "style.css")


@app.route("/script.js")
def script():
    return send_from_directory(FRONTEND_DIR, "script.js")


@app.route("/api/health")
def health():
    return jsonify({"status": "ok", "project": PROJECT_SLUG})


@app.route("/api/contact", methods=["POST"])
def contact():
    try:
        payload = request.get_json(force=True, silent=True) or {}
        name = (payload.get("name") or "").strip()
        email = (payload.get("email") or "").strip()
        message = (payload.get("message") or "").strip()
        if not name or not email or not message:
            return jsonify({"success": False, "error": "name, email and message are required"}), 400
        doc = {
            "name": name,
            "email": email,
            "message": message,
            "created_at": datetime.datetime.utcnow().isoformat(),
        }
        db_collections["contact_messages"].insert_one(doc)
        return jsonify({"success": True, "message": "Thank you, we will get back to you soon."})
    except Exception as e:
        return jsonify({"success": False, "error": str(e)}), 500


# ---- EXTRA_ROUTES_START ----
# /api/sections
@app.route('/api/sections', methods=['GET'])
def get_sections():
    try:
        return jsonify({'sections': db_collections['sections'].find({})})
    except Exception as e:
        return jsonify({'error': str(e)}), 500

# /api/unsplash_query_topics
@app.route('/api/unsplash_query_topics', methods=['GET'])
def get_unsplash_query_topics():
    try:
        return jsonify({'topics': db_collections['unsplash_query_topics'].find({})})
    except Exception as e:
        return jsonify({'error': str(e)}), 500

# /api/must_have_features
@app.route('/api/must_have_features', methods=['GET'])
def get_must_have_features():
    try:
        return jsonify({'features': db_collections['must_have_features'].find({})})
    except Exception as e:
        return jsonify({'error': str(e)}), 500

# /api/summary_for_frontend_agent
@app.route('/api/summary_for_frontend_agent', methods=['GET'])
def get_summary_for_frontend_agent():
    try:
        return jsonify({'summary': db_collections['summary_for_frontend_agent'].find({})})
    except Exception as e:
        return jsonify({'error': str(e)}), 500

# /api/pricing
@app.route('/api/pricing', methods=['GET'])
def get_pricing():
    try:
        return jsonify({'pricing': db_collections['pricing'].find({})})
    except Exception as e:
        return jsonify({'error': str(e)}), 500

# /api/testimonials
@app.route('/api/testimonials', methods=['GET'])
def get_testimonials():
    try:
        return jsonify({'testimonials': db_collections['testimonials'].find({})})
    except Exception as e:
        return jsonify({'error': str(e)}), 500

# /api/faq
@app.route('/api/faq', methods=['GET'])
def get_faq():
    try:
        return jsonify({'faq': db_collections['faq'].find({})})
    except Exception as e:
        return jsonify({'error': str(e)}), 500

# /api/contact
@app.route('/api/contact', methods=['GET'])
def get_contact():
    try:
        return jsonify({'contact': db_collections['contact'].find({})})
    except Exception as e:
        return jsonify({'error': str(e)}), 500
# ---- EXTRA_ROUTES_END ----


if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    app.run(host="0.0.0.0", port=port, debug=False)
