"""
Auto-generated Flask backend for project: Dental Health
Generated by Backend Agent. Serves the frontend at clean numeric/root URLs
(no .html in any URL) and exposes JSON APIs the frontend calls via fetch().

Also ships a built-in Admin Panel (Admin Agent output):
  - http://localhost:5000/admin        -> edit any text/image on the site
  - http://localhost:5000/details/<id> -> the page a "View Details" button opens
Log in to /admin with the password in ADMIN_PASSWORD (see this project's .env).
"""
import os
import json
import datetime
from flask import Flask, send_from_directory, jsonify, request, session
from flask_cors import CORS
from pymongo import MongoClient
from dotenv import load_dotenv
import secrets

load_dotenv()

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
FRONTEND_DIR = os.path.join(BASE_DIR, "frontend")
CONTENT_FILE = os.path.join(FRONTEND_DIR, "content.json")

app = Flask(__name__, static_folder=FRONTEND_DIR, static_url_path="")
app.secret_key = os.environ.get("ADMIN_SECRET_KEY") or secrets.token_hex(32)
CORS(app, supports_credentials=True)

ADMIN_PASSWORD = os.environ.get("ADMIN_PASSWORD", "admin123")

mongo_client = MongoClient(os.environ.get("MONGO_URI", "mongodb://localhost:27017"))
db = mongo_client[os.environ.get("MONGO_DB_NAME", "generated_website_db")]

PROJECT_SLUG = "dental_health"
db_collections = {
    "contact_messages": db["project_dental_health_contact_messages"],
    "testimonials": db["project_dental_health_testimonials"],
    "site_content": db["project_dental_health_site_content"],
}


def _default_content():
    return {"editable": {}, "details": []}


def _load_content():
    if os.path.exists(CONTENT_FILE):
        try:
            with open(CONTENT_FILE, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception:
            pass
    doc = db_collections["site_content"].find_one({"project_slug": PROJECT_SLUG, "_key": "main"})
    if doc:
        return {"editable": doc.get("editable", {}), "details": doc.get("details", [])}
    return _default_content()


def _save_content(data: dict):
    os.makedirs(FRONTEND_DIR, exist_ok=True)
    with open(CONTENT_FILE, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    try:
        db_collections["site_content"].update_one(
            {"project_slug": PROJECT_SLUG, "_key": "main"},
            {"$set": {**data, "project_slug": PROJECT_SLUG, "_key": "main"}},
            upsert=True,
        )
    except Exception:
        pass  # the JSON file on disk is still the source of truth


def _require_admin():
    return session.get("is_admin") is True


@app.route("/")
def home():
    # Serves index.html with a clean root URL — never /index.html
    return send_from_directory(FRONTEND_DIR, "index.html")


@app.route("/style.css")
def style():
    return send_from_directory(FRONTEND_DIR, "style.css")


@app.route("/script.js")
def script():
    return send_from_directory(FRONTEND_DIR, "script.js")


@app.route("/api/health")
def health():
    return jsonify({"status": "ok", "project": PROJECT_SLUG})


@app.route("/api/contact", methods=["POST"])
def contact():
    try:
        payload = request.get_json(force=True, silent=True) or {}
        name = (payload.get("name") or "").strip()
        email = (payload.get("email") or "").strip()
        message = (payload.get("message") or "").strip()
        if not name or not email or not message:
            return jsonify({"success": False, "error": "name, email and message are required"}), 400
        doc = {
            "name": name,
            "email": email,
            "message": message,
            "created_at": datetime.datetime.utcnow().isoformat(),
        }
        db_collections["contact_messages"].insert_one(doc)
        return jsonify({"success": True, "message": "Thank you, we will get back to you soon."})
    except Exception as e:
        return jsonify({"success": False, "error": str(e)}), 500


# ---------------------------------------------------------------------
# Admin Panel + "View Details" pages (built by the Admin Agent)
# ---------------------------------------------------------------------

@app.route("/admin")
def admin_panel():
    return send_from_directory(FRONTEND_DIR, "admin.html")


@app.route("/details/<detail_id>")
def details_page(detail_id):
    return send_from_directory(FRONTEND_DIR, "details.html")


@app.route("/api/content")
def public_content():
    # Public, read-only: the live page's own script loads this to apply any
    # edits made in the admin panel. Contains nothing not already visible on
    # the page itself.
    return jsonify(_load_content())


@app.route("/api/details/<detail_id>")
def api_detail(detail_id):
    data = _load_content()
    for item in data.get("details", []):
        if item.get("id") == detail_id:
            return jsonify(item)
    return jsonify({"error": "not found"}), 404


@app.route("/api/admin/login", methods=["POST"])
def admin_login():
    payload = request.get_json(force=True, silent=True) or {}
    if payload.get("password") == ADMIN_PASSWORD:
        session["is_admin"] = True
        return jsonify({"success": True})
    return jsonify({"success": False, "error": "Incorrect password"}), 401


@app.route("/api/admin/logout", methods=["POST"])
def admin_logout():
    session.pop("is_admin", None)
    return jsonify({"success": True})


@app.route("/api/admin/content", methods=["GET", "POST"])
def admin_content():
    if not _require_admin():
        return jsonify({"success": False, "error": "Not authenticated"}), 401

    if request.method == "GET":
        return jsonify(_load_content())

    payload = request.get_json(force=True, silent=True) or {}
    data = _load_content()
    if "editable" in payload and isinstance(payload["editable"], dict):
        data["editable"].update(payload["editable"])
    if "details" in payload and isinstance(payload["details"], list):
        data["details"] = payload["details"]
    _save_content(data)
    return jsonify({"success": True})


# ---- EXTRA_ROUTES_START ----
@app.route('/api/unsplash_topics', methods=['GET'])
def get_unsplash_topics():
    try:
        return jsonify(db_collections['unsplash_topics'].find_one({'business_slug': 'dental_health'})['topics'])
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/must_have_features', methods=['GET'])
def get_must_have_features():
    try:
        return jsonify(db_collections['must_have_features'].find_one({'business_slug': 'dental_health'})['features'])
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/sections', methods=['GET'])
def get_sections():
    try:
        return jsonify(db_collections['business_info'].find_one({'business_slug': 'dental_health'})['sections'])
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/business_info', methods=['GET'])
def get_business_info():
    try:
        return jsonify(db_collections['business_info'].find_one({'business_slug': 'dental_health'}))
    except Exception as e:
        return jsonify({'error': str(e)}), 500
# ---- EXTRA_ROUTES_END ----


if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    app.run(host="0.0.0.0", port=port, debug=False)
