"""
Auto-generated Flask backend for project: FitPro
Generated by Backend Agent. Serves the frontend at clean numeric/root URLs
(no .html in any URL) and exposes JSON APIs the frontend calls via fetch().
"""
import os
import datetime
from flask import Flask, send_from_directory, jsonify, request
from flask_cors import CORS
from pymongo import MongoClient
from dotenv import load_dotenv

load_dotenv()

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
FRONTEND_DIR = os.path.join(BASE_DIR, "frontend")

app = Flask(__name__, static_folder=FRONTEND_DIR, static_url_path="")
CORS(app)

mongo_client = MongoClient(os.environ.get("MONGO_URI", "mongodb://localhost:27017"))
db = mongo_client[os.environ.get("MONGO_DB_NAME", "generated_website_db")]

PROJECT_SLUG = "fitpro"
db_collections = {
    "contact_messages": db["project_fitpro_contact_messages"],
    "testimonials": db["project_fitpro_testimonials"],
}


@app.route("/")
def home():
    # Serves index.html with a clean root URL — never /index.html
    return send_from_directory(FRONTEND_DIR, "index.html")


@app.route("/style.css")
def style():
    return send_from_directory(FRONTEND_DIR, "style.css")


@app.route("/script.js")
def script():
    return send_from_directory(FRONTEND_DIR, "script.js")


@app.route("/api/health")
def health():
    return jsonify({"status": "ok", "project": PROJECT_SLUG})


@app.route("/api/contact", methods=["POST"])
def contact():
    try:
        payload = request.get_json(force=True, silent=True) or {}
        name = (payload.get("name") or "").strip()
        email = (payload.get("email") or "").strip()
        message = (payload.get("message") or "").strip()
        if not name or not email or not message:
            return jsonify({"success": False, "error": "name, email and message are required"}), 400
        doc = {
            "name": name,
            "email": email,
            "message": message,
            "created_at": datetime.datetime.utcnow().isoformat(),
        }
        db_collections["contact_messages"].insert_one(doc)
        return jsonify({"success": True, "message": "Thank you, we will get back to you soon."})
    except Exception as e:
        return jsonify({"success": False, "error": str(e)}), 500


# ---- EXTRA_ROUTES_START ----
@app.route('/api/pricing', methods=['GET'])
def api_pricing():
    try:
        pricing_data = db_collections['pricing'].find_one()
        return jsonify(pricing_data)
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/testimonials', methods=['GET'])
def api_testimonials():
    try:
        testimonials_data = db_collections['testimonials'].find()
        return jsonify([testimonial for testimonial in testimonials_data])
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/classes', methods=['GET'])
def api_classes():
    try:
        classes_data = db_collections['classes'].find()
        return jsonify([class_data for class_data in classes_data])
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/services', methods=['GET'])
def api_services():
    try:
        services_data = db_collections['services'].find()
        return jsonify([service for service in services_data])
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/gallery', methods=['GET'])
def api_gallery():
    try:
        gallery_data = db_collections['gallery'].find()
        return jsonify([image for image in gallery_data])
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/about', methods=['GET'])
def api_about():
    try:
        about_data = db_collections['about'].find_one()
        return jsonify(about_data)
    except Exception as e:
        return jsonify({'error': str(e)}), 500
# ---- EXTRA_ROUTES_END ----


if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    app.run(host="0.0.0.0", port=port, debug=False)
