"""
Auto-generated Flask backend for project: Haven Properties
Generated by Backend Agent. Serves the frontend at clean numeric/root URLs
(no .html in any URL) and exposes JSON APIs the frontend calls via fetch().
"""
import os
import datetime
from flask import Flask, send_from_directory, jsonify, request
from flask_cors import CORS
from pymongo import MongoClient
from dotenv import load_dotenv

load_dotenv()

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
FRONTEND_DIR = os.path.join(BASE_DIR, "frontend")

app = Flask(__name__, static_folder=FRONTEND_DIR, static_url_path="")
CORS(app)

mongo_client = MongoClient(os.environ.get("MONGO_URI", "mongodb://localhost:27017"))
db = mongo_client[os.environ.get("MONGO_DB_NAME", "generated_website_db")]

PROJECT_SLUG = "haven_properties"
db_collections = {
    "contact_messages": db["project_haven_properties_contact_messages"],
    "testimonials": db["project_haven_properties_testimonials"],
}


@app.route("/")
def home():
    # Serves index.html with a clean root URL — never /index.html
    return send_from_directory(FRONTEND_DIR, "index.html")


@app.route("/style.css")
def style():
    return send_from_directory(FRONTEND_DIR, "style.css")


@app.route("/script.js")
def script():
    return send_from_directory(FRONTEND_DIR, "script.js")


@app.route("/api/health")
def health():
    return jsonify({"status": "ok", "project": PROJECT_SLUG})


@app.route("/api/contact", methods=["POST"])
def contact():
    try:
        payload = request.get_json(force=True, silent=True) or {}
        name = (payload.get("name") or "").strip()
        email = (payload.get("email") or "").strip()
        message = (payload.get("message") or "").strip()
        if not name or not email or not message:
            return jsonify({"success": False, "error": "name, email and message are required"}), 400
        doc = {
            "name": name,
            "email": email,
            "message": message,
            "created_at": datetime.datetime.utcnow().isoformat(),
        }
        db_collections["contact_messages"].insert_one(doc)
        return jsonify({"success": True, "message": "Thank you, we will get back to you soon."})
    except Exception as e:
        return jsonify({"success": False, "error": str(e)}), 500


# ---- EXTRA_ROUTES_START ----
@app.route('/api/properties', methods=['GET'])
def get_properties():
    try:
        properties = db_collections['properties'].find()
        return jsonify([prop for prop in properties])
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/properties/<prop_id>', methods=['GET'])
def get_property(prop_id):
    try:
        property = db_collections['properties'].find_one({'_id': ObjectId(prop_id)})
        if property:
            return jsonify(property)
        else:
            return jsonify({'error': 'Property not found'}), 404
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/testimonials', methods=['GET'])
def get_testimonials():
    try:
        testimonials = db_collections['testimonials'].find()
        return jsonify([test for test in testimonials])
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/testimonials/<testimonial_id>', methods=['GET'])
def get_testimonial(testimonial_id):
    try:
        testimonial = db_collections['testimonials'].find_one({'_id': ObjectId(testimonial_id)})
        if testimonial:
            return jsonify(testimonial)
        else:
            return jsonify({'error': 'Testimonial not found'}), 404
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/properties/search', methods=['POST'])
def search_properties():
    try:
        data = request.get_json()
        if 'search_query' in data:
            properties = db_collections['properties'].find({'$text': {'$search': data['search_query']}})
            return jsonify([prop for prop in properties])
        else:
            return jsonify({'error': 'Search query required'}), 400
    except Exception as e:
        return jsonify({'error': str(e)}), 500
# ---- EXTRA_ROUTES_END ----


if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    app.run(host="0.0.0.0", port=port, debug=False)
