import os
import secrets
from clients.nvidia_client import NvidiaClient

EXTRA_ROUTES_SYSTEM_PROMPT = """You write small, additional Flask route handlers ONLY.
You will be given a Flask `app` object already created, MongoDB collections already
available as a dict called `db_collections`, and the business brief.
Output ONLY a single Python code block with extra @app.route(...) function
definitions (no app.run(), no app = Flask(...), no imports beyond what is
already imported: flask, pymongo, datetime). Each route must:
- live under the /api/ prefix
- return JSON via jsonify()
- handle errors with try/except and return proper status codes (never crash silently)
Do not redefine "/" or any static file route. Do not use "/api/content", "/api/details/...",
or any "/api/admin/..." path — those are already reserved by the Admin Panel. Do not include
explanations outside the code block.
"""

APP_TEMPLATE = '''"""
Auto-generated Flask backend for project: {business_name}
Generated by Backend Agent. Serves the frontend at clean numeric/root URLs
(no .html in any URL) and exposes JSON APIs the frontend calls via fetch().

Also ships a built-in Admin Panel (Admin Agent output):
  - http://localhost:5000/admin        -> edit any text/image on the site
  - http://localhost:5000/details/<id> -> the page a "View Details" button opens
Log in to /admin with the password in ADMIN_PASSWORD (see this project's .env).
"""
import os
import json
import datetime
from flask import Flask, send_from_directory, jsonify, request, session
from flask_cors import CORS
from pymongo import MongoClient
from dotenv import load_dotenv

load_dotenv()

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
FRONTEND_DIR = os.path.join(BASE_DIR, "frontend")
CONTENT_FILE = os.path.join(FRONTEND_DIR, "content.json")

app = Flask(__name__, static_folder=FRONTEND_DIR, static_url_path="")
app.secret_key = os.environ.get("ADMIN_SECRET_KEY") or secrets.token_hex(32)
CORS(app, supports_credentials=True)

ADMIN_PASSWORD = os.environ.get("ADMIN_PASSWORD", "admin123")

mongo_client = MongoClient(os.environ.get("MONGO_URI", "mongodb://localhost:27017"))
db = mongo_client[os.environ.get("MONGO_DB_NAME", "generated_website_db")]

PROJECT_SLUG = "{project_slug}"
db_collections = {{
    "contact_messages": db["{contact_collection}"],
    "testimonials": db["{testimonials_collection}"],
    "site_content": db["{site_content_collection}"],
}}


def _default_content():
    return {{"editable": {{}}, "details": [], "sections": [], "custom_fields": {{}}}}


def _normalize_content(data: dict) -> dict:
    # Backfills keys for content.json files written before "sections" /
    # "custom_fields" existed, so older generated projects keep working.
    data.setdefault("editable", {{}})
    data.setdefault("details", [])
    data.setdefault("sections", [])
    data.setdefault("custom_fields", {{}})
    return data


def _load_content():
    if os.path.exists(CONTENT_FILE):
        try:
            with open(CONTENT_FILE, "r", encoding="utf-8") as f:
                return _normalize_content(json.load(f))
        except Exception:
            pass
    doc = db_collections["site_content"].find_one({{"project_slug": PROJECT_SLUG, "_key": "main"}})
    if doc:
        return _normalize_content({{
            "editable": doc.get("editable", {{}}),
            "details": doc.get("details", []),
            "sections": doc.get("sections", []),
            "custom_fields": doc.get("custom_fields", {{}}),
        }})
    return _default_content()


def _save_content(data: dict):
    os.makedirs(FRONTEND_DIR, exist_ok=True)
    with open(CONTENT_FILE, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    try:
        db_collections["site_content"].update_one(
            {{"project_slug": PROJECT_SLUG, "_key": "main"}},
            {{"$set": {{**data, "project_slug": PROJECT_SLUG, "_key": "main"}}}},
            upsert=True,
        )
    except Exception:
        pass  # the JSON file on disk is still the source of truth


def _require_admin():
    return session.get("is_admin") is True


@app.route("/")
def home():
    # Serves index.html with a clean root URL — never /index.html
    return send_from_directory(FRONTEND_DIR, "index.html")


@app.route("/style.css")
def style():
    return send_from_directory(FRONTEND_DIR, "style.css")


@app.route("/script.js")
def script():
    return send_from_directory(FRONTEND_DIR, "script.js")


@app.route("/api/health")
def health():
    return jsonify({{"status": "ok", "project": PROJECT_SLUG}})


@app.route("/api/contact", methods=["POST"])
def contact():
    try:
        payload = request.get_json(force=True, silent=True) or {{}}
        name = (payload.get("name") or "").strip()
        email = (payload.get("email") or "").strip()
        message = (payload.get("message") or "").strip()
        if not name or not email or not message:
            return jsonify({{"success": False, "error": "name, email and message are required"}}), 400
        doc = {{
            "name": name,
            "email": email,
            "message": message,
            "created_at": datetime.datetime.utcnow().isoformat(),
        }}
        db_collections["contact_messages"].insert_one(doc)
        return jsonify({{"success": True, "message": "Thank you, we will get back to you soon."}})
    except Exception as e:
        return jsonify({{"success": False, "error": str(e)}}), 500


# ---------------------------------------------------------------------
# Admin Panel + "View Details" pages (built by the Admin Agent)
# ---------------------------------------------------------------------

@app.route("/admin")
def admin_panel():
    return send_from_directory(FRONTEND_DIR, "admin.html")


@app.route("/details/<detail_id>")
def details_page(detail_id):
    return send_from_directory(FRONTEND_DIR, "details.html")


@app.route("/api/content")
def public_content():
    # Public, read-only: the live page's own script loads this to apply any
    # edits made in the admin panel. Contains nothing not already visible on
    # the page itself.
    return jsonify(_load_content())


@app.route("/api/details/<detail_id>")
def api_detail(detail_id):
    data = _load_content()
    for item in data.get("details", []):
        if item.get("id") == detail_id:
            return jsonify(item)
    return jsonify({{"error": "not found"}}), 404


@app.route("/api/admin/login", methods=["POST"])
def admin_login():
    payload = request.get_json(force=True, silent=True) or {{}}
    if payload.get("password") == ADMIN_PASSWORD:
        session["is_admin"] = True
        return jsonify({{"success": True}})
    return jsonify({{"success": False, "error": "Incorrect password"}}), 401


@app.route("/api/admin/logout", methods=["POST"])
def admin_logout():
    session.pop("is_admin", None)
    return jsonify({{"success": True}})


@app.route("/api/admin/content", methods=["GET", "POST"])
def admin_content():
    if not _require_admin():
        return jsonify({{"success": False, "error": "Not authenticated"}}), 401

    if request.method == "GET":
        return jsonify(_load_content())

    payload = request.get_json(force=True, silent=True) or {{}}
    data = _load_content()
    if "editable" in payload and isinstance(payload["editable"], dict):
        data["editable"].update(payload["editable"])
    if "details" in payload and isinstance(payload["details"], list):
        data["details"] = payload["details"]
    if "custom_fields" in payload and isinstance(payload["custom_fields"], dict):
        data["custom_fields"] = payload["custom_fields"]
    if "sections" in payload and isinstance(payload["sections"], list):
        data["sections"] = payload["sections"]
    _save_content(data)
    return jsonify({{"success": True}})


# ---- EXTRA_ROUTES_START ----
{extra_routes}
# ---- EXTRA_ROUTES_END ----


if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    app.run(host="0.0.0.0", port=port, debug=False)
'''

def _extract_python_block(text: str) -> str:
    import re
    match = re.search(r"```python\s*(.*?)```", text, re.DOTALL | re.IGNORECASE)
    if match:
        return match.group(1).strip()
    generic = re.search(r"```\s*(.*?)```", text, re.DOTALL)
    return generic.group(1).strip() if generic else ""


class BackendAgent:
    def __init__(self, nvidia_client: NvidiaClient = None):
        self.nvidia = nvidia_client or NvidiaClient()

    def generate_extra_routes(self, brief: dict) -> str:
        prompt = f"Business brief: {brief}\nGenerate any extra /api/ routes this business specifically needs (e.g. /api/pricing, /api/testimonials GET)."
        try:
            response = self.nvidia.code(EXTRA_ROUTES_SYSTEM_PROMPT, prompt, temperature=0.3, max_tokens=2000)
            code = _extract_python_block(response)
            return code if code else "# no extra routes generated"
        except Exception:
            return "# extra route generation skipped (nvidia api unavailable)"

    def build(self, project_slug: str, brief: dict, runtime_collections: dict) -> str:
        extra_routes = self.generate_extra_routes(brief)
        app_py = APP_TEMPLATE.format(
            business_name=brief.get("business_name", "Generated Website"),
            project_slug=project_slug,
            contact_collection=runtime_collections["contact_collection"],
            testimonials_collection=runtime_collections["testimonials_collection"],
            site_content_collection=runtime_collections["site_content_collection"],
            extra_routes=extra_routes,
        )
        return app_py

    def write_to_disk(self, project_dir: str, app_py: str):
        os.makedirs(project_dir, exist_ok=True)
        with open(os.path.join(project_dir, "app.py"), "w", encoding="utf-8") as f:
            f.write(app_py)
        # requirements + a project-local .env.example so the user knows what to fill
        with open(os.path.join(project_dir, "requirements.txt"), "w", encoding="utf-8") as f:
            f.write("flask\nflask-cors\npymongo\npython-dotenv\n")
        env_example_path = os.path.join(project_dir, ".env.example")
        if not os.path.exists(env_example_path):
            with open(env_example_path, "w", encoding="utf-8") as f:
                f.write(
                    "MONGO_URI=mongodb://localhost:27017\n"
                    "MONGO_DB_NAME=generated_website_db\n"
                    "# Password to log in at http://localhost:5000/admin\n"
                    "ADMIN_PASSWORD=admin123\n"
                    "# Optional: fixed Flask session secret (auto-generated per run if left blank)\n"
                    "ADMIN_SECRET_KEY=\n"
                )